---
title: "Massachusetts Data Processing for NFDS model"
output: html_notebook
editor_options: 
  chunk_output_type: console
---


```{r}
path_to_data <- "~/Documents/PhD_Project/Data/"
```

```{r}
### Reading in the Accession Codes, Population and the Sequence Clusters
library(readxl)
Samples_accCodes <- read_excel(paste(path_to_data, "Massachusetts_data_NickCroucher/SupplementaryDataPaper/Samples_accCodes.xlsx", sep = ""))
Mass_Samples_accCodes <- Samples_accCodes[Samples_accCodes$Population=="Massachusetts",]
Mass_Isolates <- Mass_Samples_accCodes$`Isolate Name`
Mass_Isolates_dict <- 1:length(Mass_Isolates)
names(Mass_Isolates_dict) <- Mass_Isolates

Isolates <- Samples_accCodes$`Isolate Name`
Isolates_dict <- 1:length(Isolates)
names(Isolates_dict) <- Isolates

Isolate_from_Mass_dict <- rep(0, length(Isolates))
names(Isolate_from_Mass_dict) <- Isolates
Isolate_from_Mass_dict[Mass_Isolates] <- 1
```

```{r}
### Reading in the Gene Cluster information
#gene_cluster <- read.table(paste(path_to_data, "v2_Massachusetts_data_NickCroucher/gCOG_sequences/CLS00005.out", sep = ""), quote="\"", comment.char="")[ c(TRUE,FALSE), ]

#function for reading cluster files
read_cls_file <- function(path_to_file){
  read.table(path_to_file, quote="\"", comment.char="")[ c(TRUE,FALSE), ]
}

#function for splitting the COG from the gene start
split_isolate_name <- function(text_line){
  name_vec <- strsplit(strsplit(text_line,">")[[1]][2],"_")
  paste(head(name_vec[[1]],-1), collapse = "_")
}
#isolates_gene_cluster <- unlist(lapply(gene_cluster, split_isolate_name))

# filter for Mass only
#Mass_isolates_gene_cluster <- isolates_gene_cluster[Isolate_from_Mass_dict[isolates_gene_cluster]==1]

# returns the Massachusetts-specific index of any Mass COG
return_isolate_index <- function(name){
  Mass_Isolates_dict[[name]]
}
#indices_gene_clusters <- unlist(lapply(Mass_isolates_gene_cluster, return_isolate_index))
```

```{r}
# list of input files
cls_files <- list.files(paste(path_to_data, "v2_Massachusetts_data_NickCroucher/gCOG_sequences", sep = ""), full.names = TRUE, recursive = FALSE)

# empty gene presence absence matrix
gene_presence_absence <- data.frame(matrix(0, nrow = length(cls_files)+1, ncol = length(Mass_Isolates)+1))
gene_presence_absence[1,-1] <- Mass_Isolates

# reads in all input files (takes a while, around 2000 files)
isolates_in_clusters <- (lapply(cls_files, read_cls_file))

# splits isolate names, changes values in gene presence absence matrix to 1 when genes are found
for (i in 1:length(isolates_in_clusters)) {
  isolates_gene_cluster <- unlist(lapply(isolates_in_clusters[[i]], split_isolate_name))
  Mass_isolates_gene_cluster <- isolates_gene_cluster[Isolate_from_Mass_dict[isolates_gene_cluster]==1]
  indices_gene_clusters <- unlist(lapply(Mass_isolates_gene_cluster, return_isolate_index))
  help_vector <- rep(0, length(Mass_Isolates))
  help_vector[indices_gene_clusters] <- 1
  gene_presence_absence[i+1,] <- c(strsplit(tail(strsplit(cls_files[i],"/")[[1]],1),"\\.")[[1]][1], help_vector)
}
```

```{r}
saveRDS(gene_presence_absence, file = "gene_presence_absence.rds")
```


```{r}
# create time-point specific gene presence absence matrices
Mass_year_dict <- c(rep(2001,length(Mass_Samples_accCodes[Mass_Samples_accCodes$`Year of Isolation`==2001,]$`Isolate Name`)), 
                    rep(2004,length(Mass_Samples_accCodes[Mass_Samples_accCodes$`Year of Isolation`==2004,]$`Isolate Name`)),
                    rep(2007,length(Mass_Samples_accCodes[Mass_Samples_accCodes$`Year of Isolation`==2007,]$`Isolate Name`)))
names(Mass_year_dict) <- c(Mass_Samples_accCodes[Mass_Samples_accCodes$`Year of Isolation`==2001,]$`Isolate Name`, Mass_Samples_accCodes[Mass_Samples_accCodes$`Year of Isolation`==2004,]$`Isolate Name`, Mass_Samples_accCodes[Mass_Samples_accCodes$`Year of Isolation`==2007,]$`Isolate Name`)

# empty gene presence absence matrix
gene_presence_absence_2001 <- data.frame(matrix(0, nrow = length(cls_files)+1, ncol = length(Mass_Samples_accCodes[Mass_Samples_accCodes$`Year of Isolation`==2001,]$`Isolate Name`)+1))
gene_presence_absence_2001[1,-1] <- (Mass_Samples_accCodes[Mass_Samples_accCodes$`Year of Isolation`==2001,]$`Isolate Name`)
gene_presence_absence_2001[-1,1] <- gene_presence_absence[-1,1]
gene_presence_absence_2001[-1,-1] <- gene_presence_absence[-1,c(FALSE,Mass_year_dict[unlist(gene_presence_absence[1,-1])]==2001)]

gene_presence_absence_2004 <- data.frame(matrix(0, nrow = length(cls_files)+1, ncol = length(Mass_Samples_accCodes[Mass_Samples_accCodes$`Year of Isolation`==2004,]$`Isolate Name`)+1))
gene_presence_absence_2004[1,-1] <- (Mass_Samples_accCodes[Mass_Samples_accCodes$`Year of Isolation`==2004,]$`Isolate Name`)
gene_presence_absence_2004[-1,1] <- gene_presence_absence[-1,1]
gene_presence_absence_2004[-1,-1] <- gene_presence_absence[-1,c(FALSE,Mass_year_dict[unlist(gene_presence_absence[1,-1])]==2004)]

gene_presence_absence_2007 <- data.frame(matrix(0, nrow = length(cls_files)+1, ncol = length(Mass_Samples_accCodes[Mass_Samples_accCodes$`Year of Isolation`==2007,]$`Isolate Name`)+1))
gene_presence_absence_2007[1,-1] <- (Mass_Samples_accCodes[Mass_Samples_accCodes$`Year of Isolation`==2007,]$`Isolate Name`)
gene_presence_absence_2007[-1,1] <- gene_presence_absence[-1,1]
gene_presence_absence_2007[-1,-1] <- gene_presence_absence[-1,c(FALSE,Mass_year_dict[unlist(gene_presence_absence[1,-1])]==2007)]
```



### A bit of data exploration ---
# Investigating the relationship of gene frequency and the change in frequency over time

```{r}
# calculate cluster freqs per time point
gene_cluster_freqs_1 <- rep(0, length(cls_files))
for(i in 1:length(cls_files)){
  gene_cluster_freqs_1[i] <- sum(as.numeric(gene_presence_absence_2001[i+1,-1]==1))/length(gene_presence_absence_2001[1,-1])
}

#gene_cluster_freqs_1 <- rep(0, length(cls_files))
#calculate_rowSum <- function(data_row){
  #print(sum(as.numeric(data_row==1)))
#  sum(as.numeric(data_row==1))
#}
#gene_cluster_freqs_1 <- apply(gene_presence_absence_2001[-1,-1],1,calculate_rowSum)

gene_cluster_freqs_2 <- rep(0, length(cls_files))
for(i in 1:length(cls_files)){
  gene_cluster_freqs_2[i] <- sum(as.numeric(gene_presence_absence_2004[i+1,-1]==1))/length(gene_presence_absence_2004[1,-1])
}

gene_cluster_freqs_3 <- rep(0, length(cls_files))
for(i in 1:length(cls_files)){
  gene_cluster_freqs_3[i] <- sum(as.numeric(gene_presence_absence_2007[i+1,-1]==1))/length(gene_presence_absence_2007[1,-1])
}
```

```{r}
plot(1:1500, gene_cluster_freqs_1[sort.list(gene_cluster_freqs_1)[1:1500]],type = "b", lty = 1)
lines(1:1500, gene_cluster_freqs_2[sort.list(gene_cluster_freqs_1)[1:1500]], col = "#E69F00",type = "b")
lines(1:1500, gene_cluster_freqs_3[sort.list(gene_cluster_freqs_1)[1:1500]], col = "#56B4E9", type = "b")

#plot(1:length(gene_cluster_freqs_1), gene_cluster_freqs_3[sort.list(gene_cluster_freqs_1)])
```

```{r}
# Plotting the changes in gene cluster frequencies between the 1st time point and the 2nd and 3rd, respectively, including a rolling mean
# I thought maybe there would be a correlation between the gene frequency and it variability. Well, there isn't.

library(zoo)
plot(1:1500, (gene_cluster_freqs_1-gene_cluster_freqs_2)[sort.list(gene_cluster_freqs_1)[1:1500]],type = "b", lty = 1)
lines(rollmean((gene_cluster_freqs_1-gene_cluster_freqs_2), 50), col = "#E69F00", lwd = 5)

plot(1:1500, (gene_cluster_freqs_1-gene_cluster_freqs_3)[sort.list(gene_cluster_freqs_1)[1:1500]],type = "b", lty = 1)
lines(rollmean((gene_cluster_freqs_1-gene_cluster_freqs_3), 50), col = "#E69F00", lwd = 5)
```

###