---
title: "NFDS model with COGtriangles and manual sequence clusters"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
# install.packages("drat") # -- if you don't have drat installed
# drat:::add("ncov-ic")
# install.packages("odin.dust")
library(odin.dust)
#install.packages("mcstate")
library(mcstate)
# Package for derivative-free fitting in R:
library(dfoptim)
```

# import data sets from data processing:
```{r}
Mass_Samples_accCodes <- readRDS(file = "Mass_Samples_accCodes.rds")
intermed_gene_presence_absence_consensus <- readRDS(file = "intermed_gene_presence_absence_consensus.rds")
intermed_gene_presence_absence_consensus_matrix <- sapply(intermed_gene_presence_absence_consensus[-1,-1],as.double)
model_start_pop <- readRDS(file = "model_start_pop.rds")
delta_ranking <- readRDS(file = "delta_ranking.rds")
mass_cluster_freq_1 <- readRDS(file = "mass_cluster_freq_1.rds")
mass_cluster_freq_2 <- readRDS(file = "mass_cluster_freq_2.rds")
mass_cluster_freq_3 <- readRDS(file = "mass_cluster_freq_3.rds")
mass_VT <- readRDS(file = "mass_VT.rds")
```


```{r}
WF_nG_h_vP <- odin.dust::odin_dust("NFDS_Model.R")
# copy of WrightFisherModel/WrightFisher_newData_nGenotypes_haploid_PopsizeVariablePois.R
```

#define parameters for the model:
```{r}
mass_clusters <- length(unique(Mass_Samples_accCodes$SequenceCluster))
avg_cluster_freq <- rep(1/mass_clusters, mass_clusters)

params_n_vP <- list(dt = 1/36, species_no = mass_clusters,  gene_no = nrow(intermed_gene_presence_absence_consensus)-1, Pop_ini = as.double(model_start_pop), Pop_eq = as.double(model_start_pop), capacity = sum(model_start_pop), Genotypes = intermed_gene_presence_absence_consensus_matrix, sigma_f = 0.2193191513, sigma_w = 0.0007111157, prop_f = 0.3735531590, delta = delta_ranking, m = 0.0052207254, migVec = avg_cluster_freq, vaccTypes = mass_VT, v = 0.1321567425, vacc_time = 0)
```

### Running the model:
```{r}
WFmodel_nG_h_vP <- WF_nG_h_vP$new(pars = params_n_vP,
                         time = 1,
                         n_particles = 10L,
                         n_threads = 4L,
                         seed = 1L)
```


```{r}
model_squaredError <- function(params){
  all_params <- list(dt = 1/36, species_no = mass_clusters,  gene_no = nrow(intermed_gene_presence_absence_consensus)-1, Pop_ini = as.double(model_start_pop), Pop_eq = as.double(model_start_pop), capacity = sum(model_start_pop), Genotypes = intermed_gene_presence_absence_consensus_matrix, sigma_f = params[1], sigma_w = params[2], prop_f = params[3], delta = delta_ranking, m = params[4], migVec = avg_cluster_freq, vaccTypes = mass_VT, v = params[5], vacc_time = 0)
  WFmodel <- WF_nG_h_vP$new(pars = all_params,
                         time = 1,
                         n_particles = 10L,
                         n_threads = 4L,
                         seed = 1L)
  n_particles <- 10L
  n_times <- 73
  x <- array(NA, dim = c(WFmodel$info()$len, n_particles, n_times))

  for (t in seq_len(n_times)) {
    x[ , , t] <- WFmodel$run(t)
  }
  time <- x[1, 1, ]
  x <- x[-1, , ]
  #sum((x[,1,37]/sum(x[,1,37]) - (mass_cluster_freq_2/sum(mass_cluster_freq_2)))^2) + sum((x[,1,73]/sum(x[,1,73]) - (mass_cluster_freq_3/sum(mass_cluster_freq_3)))^2)
  sum(abs(x[,1,37]/sum(x[,1,37]) - (mass_cluster_freq_2/sum(mass_cluster_freq_2)))) + sum(abs(x[,1,73]/sum(x[,1,73]) - (mass_cluster_freq_3/sum(mass_cluster_freq_3))))

}

#pmcmc_sigma_f <- mcstate::pmcmc_parameter("sigma_f", 0.15, min = 0, max = 1)
#pmcmc_sigma_w <- mcstate::pmcmc_parameter("sigma_w", 0.05, min = 0, max = 1)
#pmcmc_prop_f <- mcstate::pmcmc_parameter("prop_f", 0.25, min = 0, max = 1)
#pmcmc_m <- mcstate::pmcmc_parameter("m", 0.03, min = 0, max = 1)
#pmcmc_v <- mcstate::pmcmc_parameter("v", 0.05, min = 0, max = 1)

optim_params <- c(0.2193191513, 0.0007111157, 0.3735531590, 0.0052207254, 0.1321567425)
model_squaredError(optim_params)
```


# Try fitting with optim R function
```{r}
#optim(par = c(0.15, 0.05, 0.25, 0.03, 0.05), fn = model_squaredError, method = "L-BFGS-B", lower = c(0,0,0,0,0), upper = c(1,1,1,1,1))
### does not work --> problem with convergence I think
```

```{r}
optim_fit <- nmkb(c(0.15, 0.05, 0.25, 0.03, 0.05), model_squaredError, lower=c(0,0,0,0,0), upper=c(1,1,1,1,1))
optim_fit
optim_fit <- nmkb(c(2.400584e-01, 9.981659e-05, 2.948024e-01, 7.317635e-03, 9.683020e-02), model_squaredError, lower=c(0,0,0,0,0), upper=c(1,1,1,1,1))
optim_fit <- nmkb(c(2.400549e-01, 9.981205e-05, 2.948120e-01, 7.317485e-03, 9.683313e-02), model_squaredError, lower=c(0,0,0,0,0), upper=c(1,1,1,1,1), control = c(tol = 1e-12))

### this one is working: converges
# Parameters:
# order: sigma_f, sigma_w, prop_f, migration, vaccination
# [1] 2.400584e-01 9.981659e-05 2.948024e-01 7.317635e-03 9.683020e-02
# error: 0.01071532
print(optim_fit$value/(2*mass_clusters))
# alternatively, starting with the MCMC result:
#nmkb(c(0.2193191513, 0.0007111157, 0.3735531590, 0.0052207254, 0.1321567425), model_squaredError, lower=c(0,0,0,0,0), upper=c(1,1,1,1,1))
```

```{r}
# try using dfoptim with 
ll_pois <- function(obs, model) {
  exp_noise <- 1e6

  if (is.na(obs)) {
    # Creates vector of zeros in ll with same length, if no data
    ll_obs <- numeric(length(model))
  } else {
    lambda <- model + rexp(n = length(model), rate = exp_noise)
    ll_obs <- dpois(x = obs, lambda = lambda, log = TRUE)
  }
  ll_obs
}

combined_compare <- function(state, observed, pars = NULL) {
  result <- 0
  data_size <- sum(mass_cluster_freq_1)
  model_size = 15000
  
  for (i in 1:mass_clusters){
    result <- result + ll_pois(observed[i], state[i]/model_size * data_size)
  }
  result
}

fit_dfoptim <- function(params){
  all_params <- list(dt = 1/36, species_no = mass_clusters,  gene_no = nrow(intermed_gene_presence_absence_consensus)-1, Pop_ini = as.double(model_start_pop), Pop_eq = as.double(model_start_pop), capacity = sum(model_start_pop), Genotypes = intermed_gene_presence_absence_consensus_matrix, sigma_f = params[1], sigma_w = params[2], prop_f = params[3], delta = delta_ranking, m = params[4], migVec = avg_cluster_freq, vaccTypes = mass_VT, v = params[5], vacc_time = 0)
  WFmodel <- WF_nG_h_vP$new(pars = all_params,
                         time = 1,
                         n_particles = 10L,
                         n_threads = 4L,
                         seed = 1L)
  n_particles <- 10L
  n_times <- 73
  x <- array(NA, dim = c(WFmodel$info()$len, n_particles, n_times))

  for (t in seq_len(n_times)) {
    x[ , , t] <- WFmodel$run(t)
  }
  time <- x[1, 1, ]
  x <- x[-1, , ]
  combined_compare(x[,1,37],mass_cluster_freq_2) + combined_compare(x[,1,73],mass_cluster_freq_3) 
  #sum((x[,1,37]/sum(x[,1,37]) - (mass_cluster_freq_2/sum(mass_cluster_freq_2)))^2) + sum((x[,1,73]/sum(x[,1,73]) - (mass_cluster_freq_3/sum(mass_cluster_freq_3)))^2)
  #sum(abs(x[,1,37]/sum(x[,1,37]) - (mass_cluster_freq_2/sum(mass_cluster_freq_2)))) + sum(abs(x[,1,73]/sum(x[,1,73]) - (mass_cluster_freq_3/sum(mass_cluster_freq_3))))
}

```

```{r}
optim_fit <- nmkb(c(0.15, 0.05, 0.25, 0.03, 0.05), fit_dfoptim, lower=c(0,0,0,0,0), upper=c(1,1,1,1,1), control = c(maximize = TRUE))
#$par
#[1] 0.088986864 0.014106180 0.502623721 0.009244569 0.139939554

#$value
#[1] -289.7029
```


```{r}
end_params <- rep(0,5)
end_error <- 3
for (i in 1:20) {
  start_params <- runif(5)
  optim_fit <- nmkb(start_params, model_squaredError, lower=c(0,0,0,0,0), upper=c(1,1,1,1,1))
  if(optim_fit$value < end_error){
    end_error <- optim_fit$value
    end_params <- optim_fit$par
  }
}
```



### PopPUNK

# import PopPUNK data sets

```{r}
PopPUNK_clusters <- readRDS("PopPUNK_clusters.rds")
PP_intermed_gene_presence_absence_consensus <- readRDS(file = "PP_intermed_gene_presence_absence_consensus.rds")
PP_intermed_gene_presence_absence_consensus_matrix <- sapply(PP_intermed_gene_presence_absence_consensus[-1,-1],as.double)
PP_model_start_pop <- readRDS(file = "PP_model_start_pop.rds")
#delta_ranking <- readRDS(file = "delta_ranking.rds")
PP_mass_cluster_freq_1 <- readRDS(file = "PP_mass_cluster_freq_1.rds")
PP_mass_cluster_freq_2 <- readRDS(file = "PP_mass_cluster_freq_2.rds")
PP_mass_cluster_freq_3 <- readRDS(file = "PP_mass_cluster_freq_3.rds")
PP_mass_VT <- readRDS(file = "PP_mass_VT.rds")
```

```{r}
PP_mass_clusters <- length(unique(PopPUNK_clusters$Cluster))
PP_avg_cluster_freq <- rep(1/PP_mass_clusters, PP_mass_clusters)
```

```{r}
WF_PP <- odin.dust::odin_dust("NFDS_Model.R")
```


```{r}
PP_model_squaredError <- function(params){
  all_params <- list(dt = 1/36, species_no = PP_mass_clusters,  gene_no = nrow(PP_intermed_gene_presence_absence_consensus)-1, Pop_ini = as.double(PP_model_start_pop), Pop_eq = as.double(PP_model_start_pop), capacity = sum(PP_model_start_pop), Genotypes = PP_intermed_gene_presence_absence_consensus_matrix, sigma_f = params[1], sigma_w = params[2], prop_f = params[3], delta = delta_ranking, m = params[4], migVec = PP_avg_cluster_freq, vaccTypes = PP_mass_VT, v = params[5], vacc_time = 0)
  WFmodel <- WF_PP$new(pars = all_params,
                         time = 1,
                         n_particles = 10L,
                         n_threads = 4L,
                         seed = 1L)
  n_particles <- 10L
  n_times <- 73
  x <- array(NA, dim = c(WFmodel$info()$len, n_particles, n_times))

  for (t in seq_len(n_times)) {
    x[ , , t] <- WFmodel$run(t)
  }
  time <- x[1, 1, ]
  x <- x[-1, , ]
  #sum((x[,1,37]/sum(x[,1,37]) - (PP_mass_cluster_freq_2/sum(PP_mass_cluster_freq_2)))^2) + sum((x[,1,73]/sum(x[,1,73]) - (PP_mass_cluster_freq_3/sum(PP_mass_cluster_freq_3)))^2)
  sum(abs(x[,1,37]/sum(x[,1,37]) - (PP_mass_cluster_freq_2/sum(PP_mass_cluster_freq_2)))) + sum(abs(x[,1,73]/sum(x[,1,73]) - (PP_mass_cluster_freq_3/sum(PP_mass_cluster_freq_3))))

}
```

```{r}
#library(dfoptim)
PP_optim_fit <- nmkb(c(0.15, 0.05, 0.25, 0.03, 0.05), PP_model_squaredError, lower=c(0,0,0,0,0), upper=c(1,1,1,1,1))
PP_optim_fit
# result: 
#$par
#[1] 0.15066986 0.01008679 0.01978237 0.01519036 0.04727967
#$value
#[1] 0.02361034
#MSE - but not sure how good of a metric this is. I don't think it is comparable when the number of clusters varies
PP_2nd_optim_fit <- nmkb(c(0.116952277, 0.017671568, 0.110791408, 0.008382764, 0.081406727), PP_model_squaredError, lower=c(0,0,0,0,0), upper=c(1,1,1,1,1), control = c(tol = 1e-12))
PP_2nd_optim_fit

#print(PP_optim_fit$value/(2 * PP_mass_clusters))
```

```{r}
PP_fit_dfoptim <- function(params){
  all_params <- list(dt = 1/36, species_no = PP_mass_clusters,  gene_no = nrow(PP_intermed_gene_presence_absence_consensus)-1, Pop_ini = as.double(PP_model_start_pop), Pop_eq = as.double(PP_model_start_pop), capacity = sum(PP_model_start_pop), Genotypes = PP_intermed_gene_presence_absence_consensus_matrix, sigma_f = params[1], sigma_w = params[2], prop_f = params[3], delta = delta_ranking, m = params[4], migVec = PP_avg_cluster_freq, vaccTypes = PP_mass_VT, v = params[5], vacc_time = 0)
  WFmodel <- WF_PP$new(pars = all_params,
                         time = 1,
                         n_particles = 10L,
                         n_threads = 4L,
                         seed = 1L)
  n_particles <- 10L
  n_times <- 73
  x <- array(NA, dim = c(WFmodel$info()$len, n_particles, n_times))

  for (t in seq_len(n_times)) {
    x[ , , t] <- WFmodel$run(t)
  }
  time <- x[1, 1, ]
  x <- x[-1, , ]
  combined_compare(x[,1,37],PP_mass_cluster_freq_2) + combined_compare(x[,1,73],PP_mass_cluster_freq_3) 
  #sum((x[,1,37]/sum(x[,1,37]) - (mass_cluster_freq_2/sum(mass_cluster_freq_2)))^2) + sum((x[,1,73]/sum(x[,1,73]) - (mass_cluster_freq_3/sum(mass_cluster_freq_3)))^2)
  #sum(abs(x[,1,37]/sum(x[,1,37]) - (mass_cluster_freq_2/sum(mass_cluster_freq_2)))) + sum(abs(x[,1,73]/sum(x[,1,73]) - (mass_cluster_freq_3/sum(mass_cluster_freq_3))))
}
```

```{r}
PP_optim_fit <- nmkb(c(0.15, 0.05, 0.25, 0.03, 0.05), PP_fit_dfoptim, lower=c(0,0,0,0,0), upper=c(1,1,1,1,1), control = c(maximize = TRUE))
#$par
#[1] 0.706126287 0.002706832 0.203196043 0.037237185 0.116830782

#$value
#[1] -284.5025
```


### ggCaller with manual Sequence Clusters
# import data sets from data processing:
```{r}
Mass_Samples_accCodes <- readRDS(file = "Mass_Samples_accCodes.rds")
ggC_intermed_gene_presence_absence_consensus <- readRDS(file = "ggC_intermed_gene_presence_absence_consensus.rds")
ggC_intermed_gene_presence_absence_consensus_matrix <- sapply(ggC_intermed_gene_presence_absence_consensus[-1,-1],as.double)
model_start_pop <- readRDS(file = "model_start_pop.rds")
ggC_delta_ranking <- readRDS(file = "ggC_delta_ranking.rds")
mass_cluster_freq_1 <- readRDS(file = "mass_cluster_freq_1.rds")
mass_cluster_freq_2 <- readRDS(file = "mass_cluster_freq_2.rds")
mass_cluster_freq_3 <- readRDS(file = "mass_cluster_freq_3.rds")
mass_VT <- readRDS(file = "mass_VT.rds")
```

```{r}
WF_ggC <- odin.dust::odin_dust("NFDS_Model.R")
# copy of WrightFisherModel/WrightFisher_newData_nGenotypes_haploid_PopsizeVariablePois.R
```

#define parameters for the model:
```{r}
mass_clusters <- length(unique(Mass_Samples_accCodes$SequenceCluster))
avg_cluster_freq <- rep(1/mass_clusters, mass_clusters)

params_ggC <- list(dt = 1/36, species_no = mass_clusters,  gene_no = nrow(ggC_intermed_gene_presence_absence_consensus)-1, Pop_ini = as.double(model_start_pop), Pop_eq = as.double(model_start_pop), capacity = sum(model_start_pop), Genotypes = ggC_intermed_gene_presence_absence_consensus_matrix, sigma_f = 0.2193191513, sigma_w = 0.0007111157, prop_f = 0.3735531590, delta = ggC_delta_ranking, m = 0.0052207254, migVec = avg_cluster_freq, vaccTypes = mass_VT, v = 0.1321567425, vacc_time = 0)
```

### Running the model:
```{r}
ggC_WFmodel <- WF_ggC$new(pars = params_ggC,
                         time = 1,
                         n_particles = 10L,
                         n_threads = 4L,
                         seed = 1L)
```

```{r}
ggC_fit_dfoptim <- function(params){
  all_params <- list(dt = 1/36, species_no = mass_clusters,  gene_no = nrow(ggC_intermed_gene_presence_absence_consensus)-1, Pop_ini = as.double(model_start_pop), Pop_eq = as.double(model_start_pop), capacity = sum(model_start_pop), Genotypes = ggC_intermed_gene_presence_absence_consensus_matrix, sigma_f = params[1], sigma_w = params[2], prop_f = params[3], delta = ggC_delta_ranking, m = params[4], migVec = avg_cluster_freq, vaccTypes = mass_VT, v = params[5], vacc_time = 0)
  WFmodel <- WF_ggC$new(pars = all_params,
                         time = 1,
                         n_particles = 10L,
                         n_threads = 4L,
                         seed = 1L)
  n_particles <- 10L
  n_times <- 73
  x <- array(NA, dim = c(WFmodel$info()$len, n_particles, n_times))

  for (t in seq_len(n_times)) {
    x[ , , t] <- WFmodel$run(t)
  }
  time <- x[1, 1, ]
  x <- x[-1, , ]
  combined_compare(x[,1,37],mass_cluster_freq_2) + combined_compare(x[,1,73],mass_cluster_freq_3) 
  #sum((x[,1,37]/sum(x[,1,37]) - (mass_cluster_freq_2/sum(mass_cluster_freq_2)))^2) + sum((x[,1,73]/sum(x[,1,73]) - (mass_cluster_freq_3/sum(mass_cluster_freq_3)))^2)
  #sum(abs(x[,1,37]/sum(x[,1,37]) - (mass_cluster_freq_2/sum(mass_cluster_freq_2)))) + sum(abs(x[,1,73]/sum(x[,1,73]) - (mass_cluster_freq_3/sum(mass_cluster_freq_3))))
}

```

```{r}
ggC_optim_fit <- nmkb(c(0.15, 0.05, 0.25, 0.03, 0.05), ggC_fit_dfoptim, lower=c(0,0,0,0,0), upper=c(1,1,1,1,1), control = c(maximize = TRUE))
#$par
#[1] 0.204007017 0.001151859 0.328471292 0.036942422 0.229539499

#$value
#[1] -258.7829

#better value than COGtriangles + manual seq clusters and COGtriangles + PopPUNK clusters!
```

### ggCaller + PopPUNK

```{r}
PopPUNK_clusters <- readRDS("PopPUNK_clusters.rds")
ggCPP_intermed_gene_presence_absence_consensus <- readRDS(file = "ggCPP_intermed_gene_presence_absence_consensus.rds")
ggCPP_intermed_gene_presence_absence_consensus_matrix <- sapply(ggCPP_intermed_gene_presence_absence_consensus[-1,-1],as.double)
PP_model_start_pop <- readRDS(file = "PP_model_start_pop.rds")
ggC_delta_ranking <- readRDS(file = "ggC_delta_ranking.rds")
PP_mass_cluster_freq_1 <- readRDS(file = "PP_mass_cluster_freq_1.rds")
PP_mass_cluster_freq_2 <- readRDS(file = "PP_mass_cluster_freq_2.rds")
PP_mass_cluster_freq_3 <- readRDS(file = "PP_mass_cluster_freq_3.rds")
PP_mass_VT <- readRDS(file = "PP_mass_VT.rds")
```

```{r}
PP_mass_clusters <- length(unique(PopPUNK_clusters$Cluster))
PP_avg_cluster_freq <- rep(1/PP_mass_clusters, PP_mass_clusters)
```

# Fitting the model:

```{r}
ggCPP_fit_dfoptim <- function(params){
  all_params <- list(dt = 1/36, species_no = PP_mass_clusters,  gene_no = nrow(ggCPP_intermed_gene_presence_absence_consensus)-1, Pop_ini = as.double(PP_model_start_pop), Pop_eq = as.double(PP_model_start_pop), capacity = sum(PP_model_start_pop), Genotypes = ggCPP_intermed_gene_presence_absence_consensus_matrix, sigma_f = params[1], sigma_w = params[2], prop_f = params[3], delta = ggC_delta_ranking, m = params[4], migVec = PP_avg_cluster_freq, vaccTypes = PP_mass_VT, v = params[5], vacc_time = 0)
  WFmodel <- WF_ggC$new(pars = all_params,
                         time = 1,
                         n_particles = 10L,
                         n_threads = 4L,
                         seed = 1L)
  n_particles <- 10L
  n_times <- 73
  x <- array(NA, dim = c(WFmodel$info()$len, n_particles, n_times))

  for (t in seq_len(n_times)) {
    x[ , , t] <- WFmodel$run(t)
  }
  time <- x[1, 1, ]
  x <- x[-1, , ]
  combined_compare(x[,1,37],PP_mass_cluster_freq_2) + combined_compare(x[,1,73],PP_mass_cluster_freq_3) 
  #sum((x[,1,37]/sum(x[,1,37]) - (mass_cluster_freq_2/sum(mass_cluster_freq_2)))^2) + sum((x[,1,73]/sum(x[,1,73]) - (mass_cluster_freq_3/sum(mass_cluster_freq_3)))^2)
  #sum(abs(x[,1,37]/sum(x[,1,37]) - (mass_cluster_freq_2/sum(mass_cluster_freq_2)))) + sum(abs(x[,1,73]/sum(x[,1,73]) - (mass_cluster_freq_3/sum(mass_cluster_freq_3))))
}
```

```{r}
ggCPP_optim_fit <- nmkb(c(0.15, 0.05, 0.25, 0.03, 0.05), ggCPP_fit_dfoptim, lower=c(0,0,0,0,0), upper=c(1,1,1,1,1), control = c(maximize = TRUE))
#$par
#[1] 0.160103907 0.002371829 0.379362413 0.016383435 0.202929261

#$value
#[1] -269.4351

# A little worse than ggCaller + manual seq clusters
# but might not be comparable
```






### Visualise Fits:

```{r}
source("CreateLollipopPlot.R")
```

```{r}

fit_params <- c(2.400584e-01, 9.981659e-05, 2.948024e-01, 7.317635e-03, 9.683020e-02)
better_fit_params <- c(2.400549e-01, 9.981205e-05, 2.948120e-01, 7.317485e-03, 9.683313e-02)
all_params <- list(dt = 1/36, species_no = mass_clusters,  gene_no = nrow(intermed_gene_presence_absence_consensus)-1, Pop_ini = as.double(model_start_pop), Pop_eq = as.double(model_start_pop), capacity = sum(model_start_pop), Genotypes = intermed_gene_presence_absence_consensus_matrix, sigma_f = fit_params[1], sigma_w = fit_params[2], prop_f = fit_params[3], delta = delta_ranking, m = fit_params[4], migVec = avg_cluster_freq, vaccTypes = mass_VT, v = fit_params[5], vacc_time = 0)
WFmodel <- WF_nG_h_vP$new(pars = all_params,
                         time = 1,
                         n_particles = 10L,
                         n_threads = 4L,
                         seed = 1L)
n_particles <- 10L
n_times <- 73
x <- array(NA, dim = c(WFmodel$info()$len, n_particles, n_times))
for (t in seq_len(n_times)) {
  x[ , , t] <- WFmodel$run(t)
}
time <- x[1, 1, ]
x <- x[-1, , ]
  
model_val1 <- x[,1,1]
model_val2 <- x[,1,37]
model_val3 <- x[,1,73]

model1_VT <- model_val1[which(mass_VT==1)]
model1_NVT <- model_val1[which(mass_VT==0)]
model2_VT <- model_val2[which(mass_VT==1)]
model2_NVT <- model_val2[which(mass_VT==0)]
model3_VT <- model_val3[which(mass_VT==1)]
model3_NVT <- model_val3[which(mass_VT==0)]


### COGtriangles and manual sequence clusters
lollipop_cluster_freqs(plot_title = "Vaccine Types, manual Seq Clusters",data1 = mass_cluster_freq_1[which(mass_VT==1)]/sum(mass_cluster_freq_1), data2 = mass_cluster_freq_2[which(mass_VT==1)]/sum(mass_cluster_freq_2), data3= mass_cluster_freq_3[which(mass_VT==1)]/sum(mass_cluster_freq_3), model1 = model1_VT/sum(model_val1), model2 = model2_VT/sum(model_val2), model3 = model3_VT/sum(model_val3))
lollipop_cluster_freqs(plot_title = "Non-Vaccine Types, manual Seq Clusters",data1 = mass_cluster_freq_1[which(mass_VT==0)]/sum(mass_cluster_freq_1), data2 = mass_cluster_freq_2[which(mass_VT==0)]/sum(mass_cluster_freq_2), data3= mass_cluster_freq_3[which(mass_VT==0)]/sum(mass_cluster_freq_3), model1 = model1_NVT/sum(model_val1), model2 = model2_NVT/sum(model_val2), model3 = model3_NVT/sum(model_val3))
```

```{r}
### COGtriangles and PopPUNK clusters
PP_fit_params <- c(0.15066986, 0.01008679, 0.01978237, 0.01519036, 0.04727967)
all_params <- list(dt = 1/36, species_no = PP_mass_clusters,  gene_no = nrow(PP_intermed_gene_presence_absence_consensus)-1, Pop_ini = as.double(PP_model_start_pop), Pop_eq = as.double(PP_model_start_pop), capacity = sum(PP_model_start_pop), Genotypes = PP_intermed_gene_presence_absence_consensus_matrix, sigma_f = PP_fit_params[1], sigma_w = PP_fit_params[2], prop_f = PP_fit_params[3], delta = delta_ranking, m = PP_fit_params[4], migVec = PP_avg_cluster_freq, vaccTypes = PP_mass_VT, v = PP_fit_params[5], vacc_time = 0)
WFmodel_PP <- WF_PP$new(pars = all_params,
                         time = 1,
                         n_particles = 10L,
                         n_threads = 4L,
                         seed = 1L)
n_particles <- 10L
n_times <- 73
x <- array(NA, dim = c(WFmodel_PP$info()$len, n_particles, n_times))
for (t in seq_len(n_times)) {
  x[ , , t] <- WFmodel_PP$run(t)
}
time <- x[1, 1, ]
x <- x[-1, , ]
  
PP_model_val1 <- x[,1,1]
PP_model_val2 <- x[,1,37]
PP_model_val3 <- x[,1,73]

PP_model1_VT <- PP_model_val1[which(PP_mass_VT==1)]
PP_model1_NVT <- PP_model_val1[which(PP_mass_VT==0)]
PP_model2_VT <- PP_model_val2[which(PP_mass_VT==1)]
PP_model2_NVT <- PP_model_val2[which(PP_mass_VT==0)]
PP_model3_VT <- PP_model_val3[which(PP_mass_VT==1)]
PP_model3_NVT <- PP_model_val3[which(PP_mass_VT==0)]

### COGtriangles and manual sequence clusters
lollipop_cluster_freqs(plot_title = "Vaccine Types, PopPUNK Clusters", data1 = PP_mass_cluster_freq_1[which(PP_mass_VT==1)]/sum(PP_mass_cluster_freq_1), data2 = PP_mass_cluster_freq_2[which(PP_mass_VT==1)]/sum(PP_mass_cluster_freq_2), data3= PP_mass_cluster_freq_3[which(PP_mass_VT==1)]/sum(PP_mass_cluster_freq_3), model1 = PP_model1_VT/sum(PP_model_val1), model2 = PP_model2_VT/sum(PP_model_val2), model3 = PP_model3_VT/sum(PP_model_val3))
lollipop_cluster_freqs(plot_title = "Non-Vaccine Types, PopPUNK Clusters",data1 = PP_mass_cluster_freq_1[which(PP_mass_VT==0)]/sum(PP_mass_cluster_freq_1), data2 = PP_mass_cluster_freq_2[which(PP_mass_VT==0)]/sum(PP_mass_cluster_freq_2), data3= PP_mass_cluster_freq_3[which(PP_mass_VT==0)]/sum(PP_mass_cluster_freq_3), model1 = PP_model1_NVT/sum(PP_model_val1), model2 = PP_model2_NVT/sum(PP_model_val2), model3 = PP_model3_NVT/sum(PP_model_val3))
```

